Added Some Animation to the Error Page
viveknigam3003/resuminator-landing pull request #7
Opened 2020-11-11 07:57 UTC by chinmaym07

I have made the changes .
Please Review. Finally It looks like below.
![Peek 2020-11-11 13-23](https://user-images.githubusercontent.com/44670961/98784547-4b40f100-2421-11eb-8006-cf76fb56e884.gif)

2020-11-12 06:21 UTC, viveknigam3003 requested changes
* I also see some error with MUI Typography elements. We need to look into it too.

![Screenshot (291)](https://user-images.githubusercontent.com/30192068/98903010-bf8c9a80-24dc-11eb-9a3f-5286066e9790.png)

* Also there is a warning with `no-unused-vars`.

![Screenshot (292)](https://user-images.githubusercontent.com/30192068/98903105-eb0f8500-24dc-11eb-9506-076a6cbe9780.png)

* Make everything have a motion from one direction, preferably bottom-to-top, instead of "404" sliding in from the right side of the screen

* Another thing to look at is the Responsiveness of the `404.js` page when you're making any changes. Use Chrome's Dev tools to check out the view on major devices.

__Make sure the code is clean and free of unnecessary warnings and compile time errors__ 😅

2020-11-12 06:21 UTC, viveknigam3003 commented on src/pages/404.js
> +            }}
The navigation back to Homepage `/` seems to be broken :/ 
Please Fix that

2020-11-12 07:38 UTC, chinmaym07 commented
Thanks a lot for your valuable feedback .☺️
Will rectify these error in sometime..👍🏻

2020-11-12 14:22 UTC, chinmaym07 commented
I have made the changes ..
Please Review it again. :+1:

2020-11-13 06:49 UTC, viveknigam3003 approved these changes
Great Work!! Looks good to me! 👍🥇

2020-11-13 06:52 UTC, merged

2020-11-13 07:34 UTC, chinmaym07 commented
Yeah sure.
Thanks a lot for your Review. :grinning:  :+1: